;; -*- mode: eask; lexical-binding: t -*-

(package "x-org-lint"
         "1.0.0"
         "Run org-lint on Org files")

(website-url "https://github.com/emacs-eine/x-org-lint")
(keywords "convenience")

(package-file "x-org-lint.el")
(files "bin")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "org")
(depends-on "commander")
(depends-on "ansi")
